name: isr-literature
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - pyarrow>=15.0.0
  - scikit-learn>=1.3.0
  - pip
  - pip:
    - bibtexparser==1.4.1
    - habanero==1.2.3
